-- Supabase SQL schema for LimitCo
-- Upload this file to Supabase SQL editor or use it to initialize your database.

-- Packages table for the available Fuliza packages
CREATE TABLE IF NOT EXISTS packages (
  id BIGINT PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  limit_amount INTEGER NOT NULL,
  price INTEGER NOT NULL,
  description TEXT NOT NULL,
  features JSONB NOT NULL,
  hot BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Payments table for tracking PayHero purchase requests and callbacks
CREATE TABLE IF NOT EXISTS payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  package_id BIGINT REFERENCES packages(id) ON DELETE SET NULL,
  phone_number TEXT NOT NULL,
  full_name TEXT,
  amount INTEGER NOT NULL,
  external_reference TEXT,
  checkout_request_id TEXT,
  merchant_request_id TEXT,
  transaction_id TEXT,
  response_code TEXT,
  response_description TEXT,
  status TEXT DEFAULT 'pending',
  callback_payload JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Callback logs for raw incoming webhook payloads from PayHero
CREATE TABLE IF NOT EXISTS payment_callbacks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_id BIGINT REFERENCES payments(id) ON DELETE SET NULL,
  payload JSONB NOT NULL,
  received_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Seed the pricing packages from the app data
INSERT INTO packages (id, name, limit_amount, price, description, features, hot)
VALUES
  (1, 'FULIZA 3,000', 3000, 49, 'Get instant access to 3,000 KES Fuliza limit', '["One-time fee", "Instant approval", "24/7 support"]', true),
  (2, 'FULIZA 7,500', 7500, 99, 'Get instant access to 7,500 KES Fuliza limit', '["One-time fee", "Instant approval", "24/7 support"]', true),
  (3, 'FULIZA 10,000', 10000, 140, 'Get instant access to 10,000 KES Fuliza limit', '["One-time fee", "Instant approval", "24/7 support"]', true),
  (4, 'FULIZA 12,500', 12500, 160, 'Get instant access to 12,500 KES Fuliza limit', '["One-time fee", "Instant approval", "24/7 support"]', true),
  (5, 'FULIZA 16,000', 16000, 200, 'Get instant access to 16,000 KES Fuliza limit', '["One-time fee", "Instant approval", "24/7 support"]', true),
  (6, 'FULIZA 20,000', 20000, 260, 'Get instant access to 20,000 KES Fuliza limit', '["One-time fee", "Instant approval", "24/7 support"]', true),
  (7, 'FULIZA 24,500', 24500, 310, 'Get instant access to 24,500 KES Fuliza limit', '["One-time fee", "Instant approval", "24/7 support"]', true),
  (8, 'FULIZA 29,500', 29500, 350, 'Get instant access to 29,500 KES Fuliza limit', '["One-time fee", "Instant approval", "24/7 support"]', true),
  (9, 'FULIZA 33,000', 33000, 420, 'Get instant access to 33,000 KES Fuliza limit', '["One-time fee", "Instant approval", "24/7 support"]', true),
  (10, 'FULIZA 38,500', 38500, 490, 'Get instant access to 38,500 KES Fuliza limit', '["One-time fee", "Instant approval", "24/7 support"]', true),
  (11, 'FULIZA 43,000', 43000, 560, 'Get instant access to 43,000 KES Fuliza limit', '["One-time fee", "Instant approval", "24/7 support"]', true),
  (12, 'FULIZA 50,000', 50000, 690, 'Get instant access to 50,000 KES Fuliza limit', '["One-time fee", "Instant approval", "24/7 support"]', true),
  (13, 'FULIZA 60,000', 60000, 850, 'Get instant access to 60,000 KES Fuliza limit', '["One-time fee", "Instant approval", "24/7 support", "VIP processing"]', true),
  (14, 'FULIZA 75,000', 75000, 1200, 'Get instant access to 75,000 KES Fuliza limit', '["One-time fee", "Instant approval", "24/7 support", "VIP processing"]', true),
  (15, 'FULIZA 85,000', 85000, 1450, 'Get instant access to 85,000 KES Fuliza limit', '["One-time fee", "Instant approval", "24/7 support", "VIP processing"]', true),
  (16, 'FULIZA 100,000', 100000, 1800, 'Get instant access to 100,000 KES Fuliza limit', '["One-time fee", "Instant approval", "24/7 support", "VIP processing", "Priority support"]', true),
  (17, 'FULIZA 125,000', 125000, 2500, 'Get instant access to 125,000 KES Fuliza limit', '["One-time fee", "Instant approval", "24/7 support", "VIP processing", "Priority support"]', true),
  (18, 'FULIZA 150,000', 150000, 3200, 'Get instant access to 150,000 KES Fuliza limit', '["One-time fee", "Instant approval", "24/7 support", "VIP processing", "Priority support"]', true),
  (19, 'FULIZA 175,000', 175000, 3900, 'Get instant access to 175,000 KES Fuliza limit', '["One-time fee", "Instant approval", "24/7 support", "VIP processing", "Priority support", "Dedicated manager"]', true),
  (20, 'FULIZA 200,000', 200000, 4500, 'Get instant access to 200,000 KES Fuliza limit', '["One-time fee", "Instant approval", "24/7 support", "VIP processing", "Priority support", "Dedicated manager"]', true),
  (21, 'FULIZA 250,000', 250000, 5500, 'Get instant access to 250,000 KES Fuliza limit', '["One-time fee", "Instant approval", "24/7 support", "VIP processing", "Priority support", "Dedicated manager"]', true),
  (22, 'FULIZA 300,000', 300000, 6500, 'Get instant access to 300,000 KES Fuliza limit', '["One-time fee", "Instant approval", "24/7 support", "VIP processing", "Priority support", "Dedicated manager", "Platinum status"]', true)
ON CONFLICT (id) DO NOTHING;
